language: java
jdk:
- openjdk11

addons:
    sonarcloud:
        organization: "SimoneCiferri"
        token: "59241548f1436b3cb7c80e2ad1fd86144ca659f7"

script:
- ant build
- sonar-scanner